[package]
name = "expander_compiler"
version = "0.1.0"
edition = "2021"

[profile.test]
opt-level = 3

[dependencies]
rand.workspace = true
uint.workspace = true

[workspace]
members = [
    "ec_go_lib"
]

[workspace.dependencies]
rand = "0.8.5"
uint = "0.9.5"
