name: Build libs

on:
  push:
    branches:
      - rust_rewrite

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
  
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "expander_compiler -> expander_compiler/target"
      - name: Build
        run: cargo build --release --manifest-path=expander_compiler/ec_go_lib/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: expander_compiler/target/release/libec_go_lib.*

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: build-*
          merge-multiple: true

      - name: Push built libs to another branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan rust-built-libs
          cp artifacts/libec_go_lib.* ./
          rm ./libec_go_lib.d
          git rm --cached -r .
          git add ./libec_go_lib.* -f
          git commit -m "Add built libs"
          git push -f --set-upstream origin rust-built-libs
