name: tests

on:
  push:
    branches:
      - rust_rewrite

env:
  RUSTFLAGS: "-Dwarnings"
  RUST_BACKTRACE: 1

jobs:
  Test-rust-mac:
    runs-on: macos-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "expander_compiler -> expander_compiler/target"
      - run: cargo test --manifest-path=expander_compiler/Cargo.toml
  Test-rust-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "expander_compiler -> expander_compiler/target"
      - run: cargo test --manifest-path=expander_compiler/Cargo.toml
  Test-go-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - run: cd ecgo && go test ./test/